package mygdx.game.controller.commands;

import java.io.Serializable;

public enum ServerCommand implements Serializable, Command {
    DOES_USERNAME_EXIST,
    REGISTER_USER,
    FETCH_USER,
    FIND_USER_ACCOUNT,
    HAS_ACTIVE_SESSION,
    VALIDATE_PASSWORD,
    LOGIN_PLAYER,
    LOGOUT_PLAYER,

    VALIDATE_ANSWER,
    FETCH_QUESTION,
    RESET_PASSWORD,
    CHANGE_USERNAME,
    CHANGE_PASSWORD,
    CHANGE_EMAIL,
    TOGGLE_2FA,
    SET_QUESTION,
    GET_RANK_DATA,
    GET_GAME_HISTORY,

    GET_FRIENDS,
    GET_INCOMING_FRIEND_REQUESTS,
    ACCEPT_FRIEND_REQUEST,
    REJECT_FRIEND_REQUEST,
    GET_MESSAGES,
    SEND_MESSAGE,
    SEND_FRIEND_REQUEST,
    GET_PROFILE_DATA,

    SELECT_FACTION,
    SELECT_LEADER,
    SELECT_CARD,
    DE_SELECT_CARD,

    IS_ONLINE,
    START_GAME_REQUEST,
    RANDOM_GAME_REQUEST,
    TOURNAMENT_GAME_REQUEST,
    CANCEL_GAME_REQUESTS,

    CLOSE_CONNECTION,
    ;
}
